site_name: Caesb

repo_name: '2023.1-Caesb'
repo_url: https://github.com/Interacao-Humano-Computador/2023.1-Caesb
site_url: https://2023.1-Caesb.com/

copyright: Copyright &copy; 2023 Caesb

theme:
  name: material
  language: pt-BR
  logo: assets/imagens/logo.png
  favicon: assets/imagens/logo.png

  icon:
    repo: fontawesome/brands/github

  features:
    - toc.integrate 
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

  hide: 
    - 
    
  extra:
    social:
      - icon: fontawesome/brands/mastodon
        link: https://fosstodon.org/@squidfunk
    
  plugins: 
    - search:
        lang: pt-BR

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dark blue
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Modo Claro
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: yellow
      toggle:
        icon: material/weather-night
        name: Modo Escuro

nav:
  - Home: index.md
  - Atas:
    - Atas/Reuniao01.md
    - Atas/Reuniao02.md
  - Planejamento: 
    - Aplicativo escolhido: Planejamento/aplicativo_escolhido.md
    - Metodologia: Planejamento/metodologias.md
    - Ferramentas: Planejamento/ferramentas.md
    - Cronograma: Planejamento/cronograma.md
  - Guia: 
    - Guia/Mkdocs.md

  # TESTE 1
  

  # Ordem das pastas
  # - Planejamento: 
  #     - Metodologia: 
  #     - Ferramentas: 
  #     - Cronograma: 
  #     - Aplicativos analisados: 
  # - Pré-Rastreabilidade:
  #     - Rich Picture: 
  # - Elicitação:
  #     - Perfil do usuário: 
  #     - Personas: 
  #     - Storytelling: 
  #     - Brainstorm: 
  #     - Observação: 
  #     - Priorização:
  # - Modelagem:
  #     - Cenários: 
  #     - Léxicos: 
  #     - Casos de Uso: 
  #     - Especifição Suplementar: 
  #     - Ágil:
  # - Análise de Requisitos:
  # - Pós-Rastreabilidade:
  # - Apresentações:
  #     - Etapa 1 - xx/xx/xxxx:
  #     - Etapa 2 - xx/xx/xxxx:
  #     - Etapa 3 - xx/xx/xxxx:
  #     - Etapa 4 - xx/xx/xxxx:
  #     - Etapa 5 - xx/xx/xxxx:
  #     - Etapa 6 - xx/xx/xxxx:
  #     - Etapa 7 - xx/xx/xxxx:
  #     - Entrega Final - xx/xx/xxxx:
  # - Entrega Final:
  #     - Entrega Final:
  # -Guia:
